default_stages: [ commit, merge-commit, push, manual ]
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        files: ^(src|test)\/.*
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
      - id: cmake-format
        files: ^(CMakeLists.txt|(src|test)\/.*)
      - id: cmake-lint
        files: ^(CMakeLists.txt|(src|test)\/.*)
        args: [ -c, .cmake-lint ]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ ] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
