version: "3.9"
services:
  login:
    image: localhost/openao-server:latest
    build:
      context: .
      dockerfile: tools/packager/Dockerfile
    network_mode: host
  game:
    image: localhost/openao-server:latest
    build:
      context: .
      dockerfile: tools/packager/Dockerfile
    network_mode: host
  changelog:
    image: localhost/openao-migrator:latest
    build:
      context: .
      dockerfile: tools/migrator/Dockerfile
  seed:
    image: localhost/openao-migrator:latest
    build:
      context: .
      dockerfile: tools/migrator/Dockerfile