version: "3.9"
services:
  login:
    image: ghcr.io/fygonzalo/openao_login:latest
    ports:
      - 30000:30000
  game:
    image: ghcr.io/fygonzalo/openao_game:latest
    ports:
      - 30001:30001
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=openao
      - POSTGRES_HOST_AUTH_METHOD=trust
  migration:
    image: ghcr.io/fygonzalo/openao_migration:latest
    command:
      - --username=user
      - --password=password
      - --url
      - jdbc:postgresql://postgres:5432/openao
    restart: on-failure
  seed:
    image: ghcr.io/fygonzalo/openao_seed:latest
    command:
      - --username=user
      - --password=password
      - --url
      - jdbc:postgresql://postgres:5432/openao
    restart: on-failure
