version: "3.9"
services:
  framework:
    image: localhost/openao_framework:latest
    build:
      context: .
      dockerfile: src/framework/Dockerfile
  login:
    image: localhost/openao_login:latest
    build:
      context: .
      dockerfile: src/login/Dockerfile
    depends_on:
      - framework
    ports:
      - 30000:30000
  game:
    image: localhost/openao_game:latest
    build:
      context: .
      dockerfile: src/game/Dockerfile
    depends_on:
      - framework
    ports:
      - 30001:30001
    command:
      - database_url=jdbc:postgresql://postgres:5432/openao
      - database_user=user
      - database_password=password
  migration:
    image: localhost/openao_migration:latest
    build:
      context: .
      dockerfile: db/Dockerfile
      args:
        - TYPE=changelog
  seed:
    image: localhost/openao_seed:latest
    build:
      context: .
      dockerfile: db/Dockerfile
      args:
        - TYPE=seed