version: "3.9"
services:
  server:
    build: .
    ports:
      - 30000:30000
    command:
      - database_url=jdbc:postgresql://postgres:5432/openao
      - database_user=user
      - database_password=password
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=openao
      - POSTGRES_HOST_AUTH_METHOD=trust
  migrate:
    image: liquibase/liquibase
    command:
      - --username=user
      - --password=password
      - --url
      - jdbc:postgresql://postgres:5432/openao
      - --changeLogFile=db.changelog-root.yaml
      - update
    restart: on-failure
    volumes:
      - ./db/changelog:/liquibase/changelog:z
  seed:
    image: liquibase/liquibase
    command:
      - --username=user
      - --password=password
      - --url
      - jdbc:postgresql://postgres:5432/openao
      - --changeLogFile=db.changelog-root.yaml
      - update
    restart: on-failure
    volumes:
      - ./db/seed:/liquibase/changelog:z
