version: "3.9"
services:
  login:
    image: ghcr.io/fygonzalo/openao-server:latest
    ports:
      - 30000:30000
    command: [ "openao-login" ]
    depends_on:
      - database
      - changelog
      - seed
    restart: on-failure
    network_mode: host
  game:
    image: ghcr.io/fygonzalo/openao-server:latest
    ports:
      - 30001:30001
    command: [ "openao-game" ]
    depends_on:
      - database
      - changelog
      - seed
    restart: on-failure
    network_mode: host
  changelog:
    image: ghcr.io/fygonzalo/openao-migrator:latest
    command:
      - --username=openao
      - --password=letmein
      - --url=jdbc:postgresql://localhost:5432/openao
      - --changelog-file=db.changelog-root.yaml
      - --search-path=/usr/src/openao/db/changelog
      - update
    restart: on-failure
    depends_on:
      - database
    network_mode: host
  seed:
    image: ghcr.io/fygonzalo/openao-migrator:latest
    command:
      - --username=openao
      - --password=letmein
      - --url=jdbc:postgresql://localhost:5432/openao
      - --changelog-file=db.changelog-root.yaml
      - --search-path=/usr/src/openao/db/seed
      - update
    restart: on-failure
    depends_on:
      - database
      - changelog
    network_mode: host
  database:
    image: postgres
    ports:
      - 5432:5432
    network_mode: host
    environment:
      - POSTGRES_USER=openao
      - POSTGRES_PASSWORD=letmein
      - POSTGRES_DB=openao
      - POSTGRES_HOST_AUTH_METHOD=trust
