version: "3.9"
services:
  framework:
    image: localhost/openao_framework:latest
    build:
      context: .
      dockerfile: src/framework/Dockerfile
  login:
    image: localhost/openao_login:latest
    build:
      context: .
      dockerfile: src/login/Dockerfile
    depends_on:
      - framework
  game:
    image: localhost/openao_game:latest
    build:
      context: .
      dockerfile: src/game/Dockerfile
    depends_on:
      - framework
  migration:
    image: localhost/openao_migration:latest
    build:
      context: .
      dockerfile: db/Dockerfile
      args:
        - TYPE=changelog
  seed:
    image: localhost/openao_seed:latest
    build:
      context: .
      dockerfile: db/Dockerfile
      args:
        - TYPE=seed