name: CI

on:
  push:
    branches: [ "main", "experimental2" ]
    paths-ignore:
      - 'tools/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'tools/**'


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fygonzalo/openao-devenv:latest
    steps:
      - name: Checkout the code into workspace
        uses: actions/checkout@v3
      - name: Build and test
        run: make
