name: CI

on:
  push:
    branches: [ "main", "experimental2" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code into workspace
        uses: actions/checkout@v3
      - name: Build and test
        run: make build