name: integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code into workspace
        uses: actions/checkout@v3
      - name: Prerequisites
        run: make prerequisites
      - name: Configure
        run: make configure
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Package
        run: make package
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u fygonzalo --password-stdin
          make publish CR=ghcr.io/fygonzalo
